### ISSUE TITLE
Add a link to `Hackathon Panel` in Nav

### ISSUE THREAD

**Issue by leeduckgo** [WeLightProject/github-issue-viewer#4]
<img width="531" alt="image" src="https://user-images.githubusercontent.com/12784118/157782482-9523cca3-8626-4d6f-bb5f-63163796844f.png">

is it good for panel to be show in iframe?

**Comment by qiwihui** [comment]
由于github设置了 `frame-ancestors 'none'`，无法进行iframe，屋面修改为外链

**Comment by leeduckgo** [comment]
> 由于github设置了 `frame-ancestors 'none'`，无法进行iframe，屋面修改为外链

it's better to open a new page for it( `target="blank"`) .
