### ISSUE TITLE
it seems a bug there when sorting issues by tag

### ISSUE THREAD

**Issue by leeduckgo** [WeLightProject/github-issue-viewer#5]
<img width="985" alt="image" src="https://user-images.githubusercontent.com/12784118/158012831-efb519c8-4fe4-4e37-866e-6cf1f6e24050.png">

**Comment by qiwihui** [comment]
It is due to github api request rate limit. Without an access token, the api request rate is low.

**Comment by qiwihui** [comment]
584ad974e3694de4c6c46af34649d047872c9175 fix: optimize issue count request
25a6ea5bdb3116f5164737c5ca19b518cb376e65 fix: add input for access token
